MVC mới-20210526T150824Z-001/MVC mới/ShopPizzaHut/ShopPizzaHut/ShopPizzaHut/Controllers/GiohangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopPizzaHut.Models;
using ShopPizzaHut.Models.EF;
using System.Net;
using System.Net.Mail;
using System.Text;

namespace ShopPizzaHut.Controllers
{
    public class GiohangController : Controller
    {
        private PizzaHutShopDbContext db = new PizzaHutShopDbContext();
        // GET: Giohang
        public ActionResult Index()
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            return View(giohang);
        }
        //khai bao phuong thuc them san pham vao gio hang
        public RedirectToRouteResult AddToCart(string MaSP)
        {
            if (Session["giohang"] == null)
            {
                Session["giohang"] = new List<CartItem>();
            }
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            //kiem tra san pham khach dang chon co trong gio hang chua
            if (giohang.FirstOrDefault(m => m.MaSP == MaSP) == null)//chua co trong gio hang
            {
                SanPham sp = db.SanPhams.Find(MaSP);
                CartItem newItem = new CartItem();
                newItem.MaSP = MaSP;
                newItem.TenSP = sp.TenSP;
                newItem.SoLuong = 1;
                newItem.DonGia = Convert.ToDouble(sp.Dongia);
                giohang.Add(newItem);
            }
            else//san pham da co trong gio thi se +1 so luong
            {
                CartItem cardItem = giohang.FirstOrDefault(m => m.MaSP == MaSP);
                cardItem.SoLuong++;
            }
            Session["giohang"] = giohang;
            return RedirectToAction("Index");
        }
        public RedirectToRouteResult Update(string MaSP, int txtSoluong)
        {
            //tim cartItem muon xoa
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem item = giohang.FirstOrDefault(m => m.MaSP == MaSP);
            if (item != null)
            {
                item.SoLuong = txtSoluong;
                Session["giohang"] = giohang;
            }
            return RedirectToAction("Index");
        }
        public RedirectToRouteResult DelCartItem(string MaSP)
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem item = giohang.FirstOrDefault(m => m.MaSP == MaSP);
            if (item != null)
            {
                giohang.Remove(item);
                Session["giohang"] = giohang;
            }
            return RedirectToAction("Index");
        }
        public JsonResult SendMailToUser(string Email)
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            string sMsg = "<html><body><table border='1'><caption>Thông tin đặt hàng</caption><tr><th>STT</th><th>Tên hàng</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr>";
            int i = 0;
            double tongtien = 0;
            foreach (CartItem item in giohang)
            {
                i++;
                sMsg += "<tr>";
                sMsg += "<td>" + i.ToString() + "</td>";
                sMsg += "<td>" + item.TenSP + "</td>";
                sMsg += "<td>" + item.SoLuong.ToString() + "</td>";
                sMsg += "<td>" + String.Format("{0:#,###}", item.DonGia) + "</td>";
                sMsg += "<td>" + String.Format("{0:#,###}", item.SoLuong * item.DonGia) + "</td>";
                sMsg += "</tr>";
                tongtien += item.SoLuong * item.DonGia;
            }
            sMsg += "<tr><th colspan='5'>Tổng cộng: " + String.Format("{0:#,### vnđ}", tongtien) + "</th></tr></table></body></html>";
            bool result = false;
            result = SendEmail(Email, "Thông tin đặt hàng", sMsg);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public bool SendEmail(string toEmail, string subject, string emailBody)
        {
            try
            {
                string senderEmail = System.Configuration.ConfigurationManager.AppSettings["SenderEmail"].ToString();
                string senderPassword = System.Configuration.ConfigurationManager.AppSettings["SenderPassword"].ToString();

                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Timeout = 100000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(senderEmail, senderPassword);

                MailMessage mailMessage = new MailMessage(senderEmail, toEmail, subject, emailBody);
                mailMessage.IsBodyHtml = true;
                mailMessage.BodyEncoding = UTF8Encoding.UTF8;
                client.Send(mailMessage);

                return true;
            }
            catch(Exception ex)
            {
                return false;
            }
        }
    }
}

MVC mới-20210526T150824Z-001/MVC mới/ShopPizzaHut/ShopPizzaHut/ShopPizzaHut/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopPizzaHut.Models.EF;

namespace ShopPizzaHut.Controllers
{
    public class SanPhamsController : Controller
    {
        private PizzaHutShopDbContext db = new PizzaHutShopDbContext();

        // GET: SanPhams
        public ActionResult Index(int maloaisp=0)
        {
            if(maloaisp == 0)
            {
                var sanPhams = db.SanPhams.Include(s => s.LoaiSP);
                return View(sanPhams.ToList());
            }
            else
            {
                var sanPhams = db.SanPhams.Include(s => s.LoaiSP).OrderBy(m=>m.MaLoaiSP).Where(x=>x.MaLoaiSP==maloaisp);
                return View(sanPhams.ToList());
            }
            
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,MaLoaiSP,ChiTietSP,Donvitinh,Dongia,Image")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,MaLoaiSP,ChiTietSP,Donvitinh,Dongia,Image")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC mới-20210526T150824Z-001/MVC mới/ShopPizzaHut/ShopPizzaHut/ShopPizzaHut/Views/Giohang/Index.cshtml
@model List<ShopPizzaHut.Models.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="margin-top:50px;margin-left:50px;">Giỏ hàng</h1>
@if (Model == null)
{
    <p class="text-info text-center">
        Chưa có sản phẩm nào trong giỏ hàng
    </p>
}
else
{
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <tr>
                    <th>Mã hàng</th>
                    <th>Tên hàng</th>
                    <th>Số lượng</th>
                    <th>Đơn giá</th>
                    <th>Thành tiền</th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">@item.MaSP</td>
                        <td><a target="_blank" href="@Url.Action("Details","SanPhams",new {id=item.MaSP})">@item.TenSP</a></td>
                        <td>
                            <form action="@Url.Action("Update")" method="get">
                                <input type="hidden" name="MaSP" value="@item.MaSP" />
                                <input type="number" min="1" name="txtSoLuong" value="@item.SoLuong" style="width:100px;" />
                                <button type="submit" class="btn btn-success">Cập nhật</button>
                            </form>
                        </td>
                        <td>@item.DonGia.ToString() vnđ</td>
                        <td>@item.ThanhTien.ToString() vnđ</td>
                        <td>
                            <a href="@Url.Action("DelCartItem",new { MaSP = @item.MaSP})" onclick="return confirm('Xóa sản phẩm này?');" class="btn btn-danger btn-sm">Xóa</a>
                        </td>
                    </tr>
                }
                <tr style="color:white;">
                    <td></td>
                    <td class="text-center">Tổng số lượng</td>
                    <td>@Model.Sum(m=>m.SoLuong)</td>
                    <td class="text-center">Tổng thành tiền</td>
                    <td>@Model.Sum(m=>m.ThanhTien) vnđ</td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="6" class="text-center">
                        <form action="@Url.Action("SendMailToUser","Giohang")" method="get">
                            <a>Thông tin đặt hàng - Email: </a> <input type="email" name="Email"/>
                            <input type="submit" value="Đặt hàng" onclick="SendEmail()" class="btn btn-success btn-sm" />
                            <a class="btn btn-success btn-sm" href="@Url.Action("Index","SanPhams")">
                                Tiếp tục mua hàng
                            </a>
                        </form>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <script>
        var SendEmail = function () {
            $.ajax({
                type: "Post",
                url: "/Giohang/SendMailToUser",
                success: function (data) {
                    alert("Thành công");
                    window.location = "/Home";
                }
            })
        }
    </script>
}